services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-todo
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    ports:
      - "8080:80"
    depends_on:
      - db

  node:
    image: node:22
    container_name: react-node
    working_dir: /var/www/html/frontend
    volumes:
      - ./frontend:/var/www/html/frontend
    command: tail -f /dev/null
    ports:
      - "5173:5173"

volumes:
  db-data: